AWSTemplateFormatVersion: 2010-09-09
Description: |
  
Parameters:
  
Resources:
# CLOUDFRONT DISTRIBUTION
  CloudFrontDistribution:
    Type: 'AWS::CloudFront::Distribution'
    DependsOn:
    - LoggingBucket
    Properties:
      DistributionConfig:
        Comment: 'Cloudfront Distribution pointing S3 Bucket'
        Origins:
          - DomainName: private-bucket.s3.us-east-1.amazonaws.com
            Id: s3-private-bucket
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CloudFrontOriginIdentity}'              
              HTTPPort: '80'
              HTTPSPort: '443'
              OriginProtocolPolicy: !Ref 'OriginProtocolPolicy'
              OriginKeepaliveTimeout: !Ref 'OriginKeepaliveTimeout'
              OriginReadTimeout: !Ref 'OriginReadTimeout'
              OriginSSLProtocols:
                - TLSv1
                - TLSv1.1
                - TLSv1.2
                - SSLv3
        Enabled: true
        HttpVersion: 'http2'
        Aliases:
          - !Ref 'AlternateDomainNames'
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          Compress: !Ref 'Compress'
          DefaultTTL: 0
          MaxTTL: 0
          MinTTL: 0
          SmoothStreaming: 'false'
          TargetOriginId: S3-private-bucket
          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        ViewerCertificate:
          CloudFrontDefaultCertificate: 'true'


        Logging:
          Bucket: !Sub '${LoggingBucket}.s3.amazonaws.com'

Outputs: